name: dicogram
description: Showing Dicoding students story.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^7.8.0
  cached_network_image: ^3.2.3
  camera: ^0.10.5+2
  cupertino_icons: ^1.0.2
  dio: ^5.3.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  geocoding: ^2.1.0
  get_it: ^7.6.0
  go_router: ^10.0.0
  google_maps_flutter: ^2.4.0
  image_picker: ^1.0.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  location: ^5.0.3
  lottie: ^2.5.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0

dev_dependencies:
  auto_route_generator: null
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato_regular.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand_regular.ttf
