name: dicogram
description: Showing Dicoding students story.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  auto_route: ^7.8.0
  cached_network_image: ^3.2.3
  camera: ^0.10.5+2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  geocoding: ^2.1.0
  go_router: ^10.0.0
  image_picker: ^1.0.2
  intl: ^0.18.0
  lottie: ^2.5.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0

dev_dependencies:
  auto_route_generator: null
  build_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato_regular.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand_regular.ttf
